### ISSUE TITLE
Does not work with macOS 10.15 Catalina

### ISSUE THREAD

**Issue by petebocken** [serban/menubar-ticker#4] opened 2020-01-08 12:39 UTC
App launches and runs just fine, but does not display track information for the new Apple Music app in macOS 10.15 Catalina.

**Comment by serban** [comment] 2020-01-08 15:28
Thanks for the heads-up. This is a known issue. Hope to get around to it any day now...

https://github.com/serban/menubar-ticker/issues/3#issuecomment-551895897

**Comment by serban** [comment] 2020-01-08 15:28
Duplicate of #3

**Closed by serban** 2020-01-08 15:28 UTC
